Repository honeycombio/opentelemetry-collector-symbolicator, pull requests merged in 2025-02, with the labels that each got.

#23 rel: v0.0.3
  CHANGELOG.md
Labels: no-changelog, version: no bump

#25 fix: Update path for releases
  Makefile
  RELEASING.md
  builder-config.yaml
  go.work
  go.work.sum
  symbolicatorprocessor/config.go
  symbolicatorprocessor/factory.go
  symbolicatorprocessor/file_store.go
  symbolicatorprocessor/file_store_test.go
  symbolicatorprocessor/go.mod
  symbolicatorprocessor/go.sum
  symbolicatorprocessor/s3_store.go
  symbolicatorprocessor/symbolicator.go
  symbolicatorprocessor/symbolicator_test.go
  symbolicatorprocessor/trace_processor.go
  symbolicatorprocessor/trace_processor_test.go
Labels: type: bug

#29 rel: Release v0.0.4
  CHANGELOG.md
Labels: no-changelog

#37 docs: Update README after doing some troubleshooting
  README.md
Labels: no-changelog, version: no bump

#36 feat: Remove path when looking for source files
  README.md
  symbolicatorprocessor/store.go
  symbolicatorprocessor/store_test.go
  symbolicatorprocessor/symbolicator_test.go
Labels: version: bump minor, breaking-change
